services:
  mysql:
    image: mysql:8.0
    container_name: auth_mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: SM231198
      MYSQL_DATABASE: AuthenticationDB
      MYSQL_ROOT_HOST: '%'
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql
    command:
      - --default-authentication-plugin=mysql_native_password
      - --character-set-server=utf8mb4
      - --collation-server=utf8mb4_unicode_ci
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost", "-u", "root", "-pSM231198"]
      timeout: 20s
      retries: 20
      interval: 5s

  authentication-service:
    build:
      context: .
      dockerfile: Dockerfile
    image: authentication-service:latest
    container_name: authentication-service
    ports:
      - "7079:7079"
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://mysql:3306/AuthenticationDB?useSSL=false&allowPublicKeyRetrieval=true&serverTimezone=UTC
      SPRING_DATASOURCE_USERNAME: root
      SPRING_DATASOURCE_PASSWORD: SM231198
      SPRING_JPA_HIBERNATE_DDL_AUTO: update
      SPRING_JPA_SHOW_SQL: "true"
      SPRING_JPA_PROPERTIES_HIBERNATE_DIALECT: org.hibernate.dialect.MySQLDialect
      SPRING_JPA_DATABASE_PLATFORM: org.hibernate.dialect.MySQLDialect
      SPRING_DATASOURCE_HIKARI_CONNECTION_TIMEOUT: "60000"
      SERVER_PORT: "7079"
      SPRING_AUTOCONFIGURE_EXCLUDE: "org.springframework.boot.autoconfigure.data.redis.RedisAutoConfiguration,org.springframework.boot.autoconfigure.data.redis.RedisRepositoriesAutoConfiguration"
      SPRING_DATA_REDIS_REPOSITORIES_ENABLED: "false"
    depends_on:
      mysql:
        condition: service_healthy
    restart: on-failure:10

volumes:
  mysql_data: