spring:
  application:
    name: AuthenticationService
  data:
    redis:
      host: redis
      port: 6379
      timeout: 60000ms
      lettuce:
        pool:
          max-active: 8
          max-idle: 8
          min-idle: 0

  datasource:
    url: jdbc:mysql://localhost:3306/AuthenticationDB
    username: root
    password: SM231198
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: update

    show-sql: true

    properties:
      hibernate:
        format_sql: true

  main:
    allow-circular-references: true

logging:
  level:
    org.springframework.security: DEBUG
    org.springframework.security.oauth2: DEBUG
    org.springframework.web: DEBUG
    org.springframework.web.client: DEBUG
    org.apache.hc.client5.http: DEBUG


server:
  port: 7079

